### ISSUE TITLE
Problem with NULL in MainstreamSupportEndDate

### ISSUE THREAD

**Issue by reharmsen** [jadarnel27/SqlServerVersionScript#11]
After fixing #9 and running the produced SQL I get the following error:

Msg 515, Level 16, State 2, Line 1
Cannot insert the value NULL into column 'MainstreamSupportEndDate', table 'DBADB.dbo.SqlServerVersions'; column does not allow nulls. INSERT fails.

It seems this is the one giving the problem:
(12, 6024, 'SP3 ', 'https://support.microsoft.com/en-us/help/4022619', '2018-10-30', NULL, NULL, 'SQL Server 2014', 'Service Pack 3 '),

**Comment by reharmsen** [comment]
I created a workaround for this one to see #12

**Comment by jadarnel27** [comment]
You rock with these pull requests, @reharmsen!  I'm putting out a release now.
