### ISSUE TITLE
Add a primary key to SqlServerVersions table

### ISSUE THREAD

**Issue by reharmsen** [jadarnel27/SqlServerVersionScript#2]
The SqlServerVersions table does not contain a primary key, this won't allow us to replicate this table through our central DBADA database.

One way would be to create a clustered key on 'MajorVersionNumber', 'MinorVersionNumber' and 'ReleaseDate', this can be done by adding this to the table creation.

CONSTRAINT [PK_SqlServerVersions] PRIMARY KEY CLUSTERED
(
[MajorVersionNumber] ASC,
[MinorVersionNumber] ASC,
[ReleaseDate] ASC
)

**Comment by jadarnel27** [comment]
Sounds great to me!  I didn't really consider replication when working on this.  Thanks for bringing it up!

I'll plan on getting to it this weekend.

**Comment by jadarnel27** [comment]
@reharmsen I've published a new release that includes this fix, let me know if you have any issues with it!
